# Tensors

## 1.1 Introduction to Tensors

**Tensors** is the fundamental data structure, a multidimensional array in PyTorch. It is metaphorical relatable to the numpy array of Numpy. The difference between the two is that tensors are available in two modes: `CPU and GPU`. We will touch this mentioned feature at the end of this tutorial.
<br>
<br>
There are a few ways to build a tensor:
- `torch.arange()`
- `torch.ones()`
- `torch.zeros()`
- `torch.rand()`
- `torch.randint()`
- `torch.fromnumpy()`

In [1]:
import torch
import numpy as np

`torch.arange(n,m)` returns a 1-dimensional tensor with values ranging from $n$ to $m-1$ 

In [2]:
tensor = torch.arange(0,20)
print(tensor)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])


`torch.ones(dim_0,dim_1,...,dim_n)` returns a tensor of ones of the shape $ dim_{0} \times dim_{1} \times...\times dim_{n} $

In [3]:
print(torch.ones(3,4,6))

tensor([[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]])


`torch.zeros(dim_0,dim_1,...,dim_n)` returns a tensor of zeros of the shape $ dim_{0} \times dim_{1} \times...\times dim_{n} $

In [4]:
print(torch.zeros(3,4,6))

tensor([[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]])


`torch.rand(dim_0, dim_1,...,dim_m)` returns a tensor filled with random floats ranging from $0$ to $1$.

In [5]:
print(torch.rand(3,4,6))

tensor([[[0.2285, 0.4276, 0.8271, 0.0772, 0.2831, 0.5630],
         [0.7897, 0.6106, 0.0617, 0.0865, 0.3725, 0.1337],
         [0.9258, 0.3545, 0.7063, 0.0228, 0.9724, 0.9281],
         [0.7680, 0.3925, 0.1822, 0.3117, 0.4788, 0.1050]],

        [[0.2714, 0.7694, 0.7631, 0.2606, 0.1142, 0.1005],
         [0.8452, 0.9153, 0.8605, 0.1690, 0.1619, 0.7595],
         [0.6912, 0.4550, 0.1193, 0.2934, 0.8134, 0.1963],
         [0.0552, 0.2523, 0.2630, 0.9436, 0.2577, 0.6422]],

        [[0.8944, 0.0695, 0.8053, 0.0021, 0.7835, 0.8281],
         [0.2210, 0.2222, 0.9241, 0.9937, 0.8235, 0.8775],
         [0.6407, 0.1401, 0.0781, 0.8441, 0.0758, 0.2169],
         [0.0772, 0.0298, 0.2859, 0.7266, 0.5532, 0.6378]]])


## 1.2 Mathematical Operations on Tensors

### Normal Operations vs Inplace Operations

#### Normal Operations

We first initialize $t_1$ and $t_2$ tensor and check their tensor storage location.

In [6]:
t1 = torch.rand(3,2)
t2 = torch.rand(3,2)
print("t1: \n"+str(t1))
print("t2: \n"+str(t2))

loc_t1 = t1.data_ptr()
loc_t2 = t2.data_ptr()
print("\nTensor storage location of t1: " + str(loc_t1))
print("Tensor storage location of t2: " + str(loc_t2))

t1: 
tensor([[0.3663, 0.2878],
        [0.4093, 0.7040],
        [0.7466, 0.4743]])
t2: 
tensor([[0.8328, 0.8826],
        [0.5961, 0.9508],
        [0.1856, 0.5396]])

Tensor storage location of t1: 1543902690176
Tensor storage location of t2: 1543902686912


Now we will do normal addition on $t_1$ with $t_2$. Note that when you run the cell below everytime, the tensor storage location of $t_1$ will change.

In [7]:
# Normal addition

t1 = t1.add(t2)
print("Value of normal addition: \n" + str(t1))
loc_normalAdd = t1.data_ptr()
print("Tensor storage location of t1: " + str(loc_normalAdd))

print("\nIs the tensor storage location of t1 before and after normal addition same: " + str(loc_normalAdd==loc_t1))

Value of normal addition: 
tensor([[1.1991, 1.1704],
        [1.0054, 1.6549],
        [0.9322, 1.0139]])
Tensor storage location of t1: 1543902691840

Is the tensor storage location of t1 before and after normal addition same: False


#### Inplace Operations

Now we will look into inplace operation. Inplace operations are always post-fixed with a trailing `_`. First of all, we wiil reinitialization $t_1$ and $t_2$ tensor and check their tensor storage location.

In [8]:
t1 = torch.rand(3,2)
t2 = torch.rand(3,2)
print("t1: \n"+str(t1))
print("t2: \n"+str(t2))

loc_t1 = t1.data_ptr()
loc_t2 = t2.data_ptr()
print("\nTensor storage location of t1: " + str(loc_t1))
print("Tensor storage location of t2: " + str(loc_t2))

t1: 
tensor([[0.6708, 0.8897],
        [0.4758, 0.7601],
        [0.7696, 0.8468]])
t2: 
tensor([[0.1715, 0.2010],
        [0.9651, 0.7610],
        [0.9869, 0.6123]])

Tensor storage location of t1: 1543902689728
Tensor storage location of t2: 1543902690176


In [9]:
# Inplace addition

t1 = t1.add_(t2)
print("Value of normal addition: \n" + str(t1))
loc_normalAdd = t1.data_ptr()
print("Tensor storage location of t1: " + str(loc_normalAdd))

print("\nIs the tensor storage location of t1 before and after normal addition same: " + str(loc_normalAdd==loc_t1))

Value of normal addition: 
tensor([[0.8423, 1.0906],
        [1.4409, 1.5211],
        [1.7565, 1.4591]])
Tensor storage location of t1: 1543902689728

Is the tensor storage location of t1 before and after normal addition same: True


### Basic Mathematical Operations

First of all, let's initialize two tensors which are $t_1$ and $t_2$.

In [10]:
t1 = torch.rand(3,2)
t2 = torch.rand(3,2)
print("t1: \n"+str(t1))
print("t2: \n"+str(t2))

t1: 
tensor([[0.4112, 0.6493],
        [0.6791, 0.3544],
        [0.3705, 0.0969]])
t2: 
tensor([[0.4592, 0.2616],
        [0.9952, 0.9756],
        [0.6004, 0.9060]])


#### Addition

In [11]:
tensorAdd = torch.add(t1, t2)
print("Addition of t1 and t2: \n" + str(tensorAdd))

Addition of t1 and t2: 
tensor([[0.8704, 0.9109],
        [1.6743, 1.3300],
        [0.9709, 1.0030]])


#### Subtraction

In [12]:
tensorSub = torch.sub(t1, t2)
print("Subtraction of t1 and t2: \n" + str(tensorSub))

Subtraction of t1 and t2: 
tensor([[-0.0480,  0.3876],
        [-0.3161, -0.6212],
        [-0.2299, -0.8091]])


#### Multiplication

`torch.mul(t1, t2)` - scalar/element-wise multiplication  <br /> 
`torch.mm(t1, t2)` - matrix multiplication

Scalar multiplication required two tensors with same size. 
>Lets say tensor $t_1$ has $n \times m$ dimension, then tensor $t_2$ should also have $n \times m$ dimension in order to perform scalar multiplication. <br>The tensor size of scalar multiplication will be same as the tensor element size $n \times m$.

In [13]:
print("Size of t1: " + str(t1.shape))
print("Size of t2: " + str(t2.shape))
tensorMul = torch.mul(t1, t2)
print("\nScalar multiplication of t1 and t2: \n" + str(tensorMul))
print("Size of tensorMul: " + str(tensorMul.shape))

Size of t1: torch.Size([3, 2])
Size of t2: torch.Size([3, 2])

Scalar multiplication of t1 and t2: 
tensor([[0.1888, 0.1699],
        [0.6758, 0.3457],
        [0.2225, 0.0878]])
Size of tensorMul: torch.Size([3, 2])


In [14]:
mat_1 = torch.rand(3,3)
mat_2 = torch.rand(3,3)
print(mat_1.mm(mat_2))

tensor([[0.1615, 0.1385, 0.2428],
        [0.4428, 0.3705, 0.6398],
        [0.3831, 0.3640, 0.6676]])


Matrix multiplication requires two tensors that fulfills the following conditions, where:  
>Let's say tensor $t_1$ has $n \times m$ dimension, then tensor $t_2$ must has $m \times p$ dimension in order to perform matrix multiplication.<br>
The resulting tensor size of matrix multiplication between $t_1$ and $t_2$ will be $n \times p$.

In [15]:
print("Size of t1: " + str(t1.shape))
print("Size of t2: " + str(t2.shape))
try:
    tensorMM = torch.mm(t1, t2)
    print("\nMatrix multiplication of t1 and t2: \n" + str(tensorMM))
    print("Size of tensorMM: " + str(tensorMM.shape))
except Exception as e:
    print(e)

Size of t1: torch.Size([3, 2])
Size of t2: torch.Size([3, 2])
size mismatch, m1: [3 x 2], m2: [3 x 2] at ..\aten\src\TH/generic/THTensorMath.cpp:41


Error above shows `size mismatch`, because $t_2$ size does not match. In order to perform matrix multiplication, let's transpose t2 using `t2.T`.

In [16]:
t2_T = t2.T
print("Size of t1: " + str(t1.shape))
print("Size of t2: " + str(t2_T.shape))
tensorMM = torch.mm(t1, t2_T)
print("\nMatrix multiplication of t1 and t2: \n" + str(tensorMM))
print("Size of tensorMM: " + str(tensorMM.shape))

Size of t1: torch.Size([3, 2])
Size of t2: torch.Size([2, 3])

Matrix multiplication of t1 and t2: 
tensor([[0.3587, 1.0427, 0.8352],
        [0.4046, 1.0215, 0.7288],
        [0.1955, 0.4633, 0.3103]])
Size of tensorMM: torch.Size([3, 3])


#### Exponential

For every element x in the tensor, apply exponential function $e^{x}$

In [17]:
tensorExp = torch.exp(t1)
print("Exponential of t1: \n" + str(tensorExp))

Exponential of t1: 
tensor([[1.5087, 1.9142],
        [1.9721, 1.4253],
        [1.4485, 1.1018]])


#### Sigmoid

For every element x in the tensor, apply sigmoid function $\frac{1}{1+e^{-x}}$


In [18]:
tensorSig = torch.sigmoid(t1)
print("Sigmoid of t1: \n" + str(tensorSig))

Sigmoid of t1: 
tensor([[0.6014, 0.6568],
        [0.6635, 0.5877],
        [0.5916, 0.5242]])


## Reduction Operations

In [19]:
t1 = torch.rand(3,2)
t2 = torch.rand(3,2)
print("t1: \n"+str(t1))
print("t2: \n"+str(t2))

t1: 
tensor([[0.5217, 0.4741],
        [0.8540, 0.7760],
        [0.5798, 0.4229]])
t2: 
tensor([[0.0783, 0.4557],
        [0.1646, 0.4775],
        [0.5989, 0.4029]])


### Argmax

Returns the indices of the maximum value of all elements in the input tensor.

If no axix is specified, it will flatten the tensor and return the index of maximum value of all elements in the tensor.

In [20]:
torch.argmax(t1)

tensor(2)

`axis=0` will return the indices of the maximum value of each elements in each coloumns in the tensor.

In [21]:
torch.argmax(t1, axis=0)

tensor([1, 1])

`axis=1` will return the indices of the maximum value of each elements in each rows in the tensor.

In [22]:
torch.argmax(t1, axis=1)

tensor([0, 0, 0])

### Sum

Returns the sum of all elements in the input tensor.

In [23]:
tensor1Sum = torch.sum(t1)
print("Sum of the tensor t1: " + str(float(tensor1Sum)))

Sum of the tensor t1: 3.628380537033081


In [24]:
tensor2Sum = torch.sum(t2)
print("Sum of the tensor t2: " + str(float(tensor2Sum)))

Sum of the tensor t2: 2.177807331085205


## 1.3 Tensor Indexing, Slicing, Joining, Mutating

### Indexing and Slicing

Tensor indexing and slicing is similar to that of `numpy`:<br>

>To get the element with indices $(x,y,z)$ in tensor $a$:<br> 
`element = a[x,y,z]`

>To slice a part of the tensor $a$ in range $(x_1->x_2,y_1->y_2,z_1->z_2)$:<br> 
`slice = a[x_1:x_2+1,y_1:y_2+1,z_1:z_2+1]`

In [25]:
# Indexing and Slicing
t_1 = torch.randint(100,(2,2,7))
print(t_1)

tensor([[[87, 25, 56, 93, 64, 59, 22],
         [28, 62, 44,  8, 74, 42, 72]],

        [[63, 81, 70, 76, 20, 73, 20],
         [27, 31, 47, 74, 13, 56,  7]]])


Let's try to get the element with index $(1,1,3)$ from $t_1$

In [26]:
print(int(t_1[1,1,3]))

74


Let's try to slice out a portion of the tensor from $(0->1,1,3->6)$

In [27]:
print(t_1[:,1,3:7])

tensor([[ 8, 74, 42, 72],
        [74, 13, 56,  7]])


### Joining and Splitting

Just like in Numpy arrays, PyTorch tensors are able to join with each other. There are a few tensor methods that allow joining:
- `torch.cat((tensor_1,tensor_2), ndim)`
- `torch.stack((tensor_1,tensor_2), ndim)`

For example, let's join $t_1$ and $t_2$ at all of their dimensions respectively.

In [28]:
# Joining
# tensor.cat()
t_2 = torch.randint(100,(2,2,7))
join_0 = torch.cat((t_1,t_2),0)
join_1 = torch.cat((t_1,t_2),1)
join_2 = torch.cat((t_1,t_2),2)
print("Concatenation at dimension 0: \n"+ str(join_0), end="\n\n")
print("Concatenation at dimension 1: \n"+ str(join_1), end="\n\n")
print("Concatenation at dimension 2: \n"+ str(join_2), end="\n\n")

Concatenation at dimension 0: 
tensor([[[87, 25, 56, 93, 64, 59, 22],
         [28, 62, 44,  8, 74, 42, 72]],

        [[63, 81, 70, 76, 20, 73, 20],
         [27, 31, 47, 74, 13, 56,  7]],

        [[59, 29, 80,  9, 57, 59,  3],
         [98, 82,  3, 64, 27, 10, 33]],

        [[17, 21, 15, 97, 81, 78, 39],
         [94, 52,  1, 20, 19, 25,  3]]])

Concatenation at dimension 1: 
tensor([[[87, 25, 56, 93, 64, 59, 22],
         [28, 62, 44,  8, 74, 42, 72],
         [59, 29, 80,  9, 57, 59,  3],
         [98, 82,  3, 64, 27, 10, 33]],

        [[63, 81, 70, 76, 20, 73, 20],
         [27, 31, 47, 74, 13, 56,  7],
         [17, 21, 15, 97, 81, 78, 39],
         [94, 52,  1, 20, 19, 25,  3]]])

Concatenation at dimension 2: 
tensor([[[87, 25, 56, 93, 64, 59, 22, 59, 29, 80,  9, 57, 59,  3],
         [28, 62, 44,  8, 74, 42, 72, 98, 82,  3, 64, 27, 10, 33]],

        [[63, 81, 70, 76, 20, 73, 20, 17, 21, 15, 97, 81, 78, 39],
         [27, 31, 47, 74, 13, 56,  7, 94, 52,  1, 20, 19, 25,  3]]

><i>Note:</i> During concatenation using `torch.cat()`, all of the dimensions except the dimension that is subject to concatenation have to be of the same size 
<br><br> For example, if we have tensor $a$ and $b$, with shape $(3,2,4)$ and $(3,7,4)$ respectively, concatenation on dimension 1 is only valid 

In [29]:
# Correct concatenation
a = torch.randint(100,(3,2,4))
b = torch.randint(100,(3,7,4))
print(torch.cat((a,b),1))

tensor([[[39, 65, 98, 24],
         [38, 77, 58, 78],
         [74, 43,  5, 30],
         [55, 90, 57, 60],
         [94, 62, 44, 26],
         [28, 63, 35, 17],
         [62, 42, 58, 79],
         [74, 87, 26, 24],
         [26, 12, 24, 23]],

        [[24, 45, 62, 85],
         [40, 48,  2, 12],
         [62, 56, 97, 53],
         [83, 80, 51, 20],
         [78, 66, 38, 62],
         [46, 76, 88, 56],
         [38, 77, 44, 86],
         [23, 44, 41, 36],
         [83, 99, 68, 12]],

        [[27, 73, 72, 71],
         [66, 34, 31, 26],
         [95, 16, 85,  2],
         [ 9, 63, 57, 51],
         [98, 71, 72,  5],
         [33,  5, 48, 82],
         [44, 78, 69, 90],
         [33,  7, 17, 95],
         [38, 55, 45, 17]]])


In [30]:
# Error in concatenation
try:
    print(torch.cat((a,b),0))
except Exception as e:
    print(e)

Sizes of tensors must match except in dimension 0. Got 2 and 7 in dimension 1 (The offending index is 1)


We could also use `torch.stack()` to join two tensors. This function will stack two tensors on a new dimension with the condition that **both tensors are of the same shape**.

In [31]:
c = torch.randint(100,(3,2,4))
print(torch.stack((a,c)))

tensor([[[[39, 65, 98, 24],
          [38, 77, 58, 78]],

         [[24, 45, 62, 85],
          [40, 48,  2, 12]],

         [[27, 73, 72, 71],
          [66, 34, 31, 26]]],


        [[[ 5, 12, 54, 68],
          [19, 79, 24, 42]],

         [[26, 25, 30, 65],
          [70, 26,  3,  6]],

         [[12, 27, 97, 16],
          [37, 66, 35, 51]]]])


PyTorch also provides ways to split up tensors on dimension specified, namely:
- `torch.split(tensor, split_size_or_section_size, n_dim)`
- `torch.chunk(tensor, number_of_chunks, n_dim)`

In [32]:
# splitting with chunk size
tensor = torch.arange(0,50).reshape(5,2,5)
split1, split2 = torch.split(tensor,3,0)
print("split 1: \n"+str(split1),end="\n\n")
print("split 1: \n"+str(split2),end="\n\n")

# splitting with section_size list [1,2,2]
section1, section2, section3 = torch.split(tensor,[1,2,2],0)
print("section 1:\n"+str(section1), end="\n\n")
print("section 2:\n"+str(section2), end="\n\n")
print("section 3:\n"+str(section3), end="\n\n")

# chunking
split1, split2 = torch.chunk(tensor,2,0)
print("chunk1: \n"+str(split1), end="\n\n")
print("chunk2: \n"+str(split2), end="\n\n")

split 1: 
tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]])

split 1: 
tensor([[[30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49]]])

section 1:
tensor([[[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]])

section 2:
tensor([[[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]])

section 3:
tensor([[[30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49]]])

chunk1: 
tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]])

chunk2: 
tensor([[[30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
      

### Mutating
There are three main parts in tensor mutating:
1. Transposing
2. Squeezing
3. Unsqueezing

**Transposing** 
<br>Transposing could be performed through 3 ways:
- `torch.t() or tensor.t()`            - Only workable on 2_d tensors
- `tensor.T`                           - Returns the tensors with all its dimensions reversed (1,2,4)->(4,2,1)
- `torch.transpose(tensor, dim_0, dim_1)`- Performs transpose on any two dimensions specified

In [33]:
tensor_2d = torch.arange(0,30).reshape(5,6)
tensor_3d = tensor_2d.reshape(2,5,3)

In [34]:
print(torch.t(tensor_2d))
print(tensor_2d.t())

tensor([[ 0,  6, 12, 18, 24],
        [ 1,  7, 13, 19, 25],
        [ 2,  8, 14, 20, 26],
        [ 3,  9, 15, 21, 27],
        [ 4, 10, 16, 22, 28],
        [ 5, 11, 17, 23, 29]])
tensor([[ 0,  6, 12, 18, 24],
        [ 1,  7, 13, 19, 25],
        [ 2,  8, 14, 20, 26],
        [ 3,  9, 15, 21, 27],
        [ 4, 10, 16, 22, 28],
        [ 5, 11, 17, 23, 29]])


In [35]:
print(tensor_3d.T)
print(tensor_3d.shape)

tensor([[[ 0, 15],
         [ 3, 18],
         [ 6, 21],
         [ 9, 24],
         [12, 27]],

        [[ 1, 16],
         [ 4, 19],
         [ 7, 22],
         [10, 25],
         [13, 28]],

        [[ 2, 17],
         [ 5, 20],
         [ 8, 23],
         [11, 26],
         [14, 29]]])
torch.Size([2, 5, 3])


In [36]:
print(torch.transpose(tensor_3d, 2, 1))
print(torch.transpose(tensor_3d, 2, 1).shape)

tensor([[[ 0,  3,  6,  9, 12],
         [ 1,  4,  7, 10, 13],
         [ 2,  5,  8, 11, 14]],

        [[15, 18, 21, 24, 27],
         [16, 19, 22, 25, 28],
         [17, 20, 23, 26, 29]]])
torch.Size([2, 3, 5])


**Squeezing**
<br>Just like what the name suggests, squeezing helps to remove redundant dimensions with value of one. The function is as follows:

`torch.squeeze(tensor, dim)`

The function removes all dimensions with value 1 if no dimension is specified.

In [37]:
tensor = torch.arange(0,20).reshape(1,5,2,1,2)
print("Shape before squeezing: ")
print(tensor.shape)
tensor_squeezed = torch.squeeze(tensor)
print("Shape after squeezing: ")
print(tensor_squeezed.shape)

Shape before squeezing: 
torch.Size([1, 5, 2, 1, 2])
Shape after squeezing: 
torch.Size([5, 2, 2])


In [38]:
# squeezing only dimension 3
tensor_squeezed = torch.squeeze(tensor,3)
print("Shape before squeezing: ")
print(tensor.shape)
print("Shape after squeezing dimension 3: ")
print(tensor_squeezed.shape)

Shape before squeezing: 
torch.Size([1, 5, 2, 1, 2])
Shape after squeezing dimension 3: 
torch.Size([1, 5, 2, 2])


**Unsqueeze**
<br>Sometimes we would like our tensor to match a certain dimension so that we could perform matrix operations like broadcasting. In this case we would like our tensors to be padded with extra dimensions.
<br> What we could do is to "unsqueeze" the matrix. 
- `torch.unsqueeze(tensor,dim)`
- `tensor.unsqueeze(dim)`
- `tensor.unsqueeze_(dim)`- inplace-operator

In [39]:
tensor = torch.arange(0,10)
print("Shape before unsqueeze:")
print(tensor.shape)
tensor.unsqueeze_(0)
print("Shape after unsqueeze:")
print(tensor.shape)

Shape before unsqueeze:
torch.Size([10])
Shape after unsqueeze:
torch.Size([1, 10])


In [40]:
# specifying tensor dimension to unsqueeze
tensor.unsqueeze_(2)
tensor.shape

torch.Size([1, 10, 1])

## 1.4 Tensor objects methods

There are a lot of useful methods provided by tensor objects. In this section, we will provide some examples on commonly used tensor object methods in deep learning.
<br>
If you wish to know more on tensor object methods, you can access it at [here](https://pytorch.org/docs/stable/tensors.html)

In [41]:
# Initializing tensor
tensor_1 = torch.tensor([[1,2], [3,4], [8,9]])
tensor_2 = torch.tensor([[5,6], [7,8]])
print("Tensor 1: \n", tensor_1)
print("Tensor 2: \n", tensor_2)

# We can flatten the tensor into single dimension by just calling tensor.flatten() 
flat = tensor_1.flatten()
print(flat)

Tensor 1: 
 tensor([[1, 2],
        [3, 4],
        [8, 9]])
Tensor 2: 
 tensor([[5, 6],
        [7, 8]])
tensor([1, 2, 3, 4, 8, 9])


To perform matric multiplication, this could be done in two ways


1.   `torch.mm(tensor1,tensor2)`
2.   `tensor.mm(tensor2)`

Either way will produce the same result

In [42]:
torch_mm = torch.mm(tensor_1, tensor_2)
print(torch_mm)

tensor_mm = tensor_1.mm(tensor_2)
print(tensor_mm)

tensor([[ 19,  22],
        [ 43,  50],
        [103, 120]])
tensor([[ 19,  22],
        [ 43,  50],
        [103, 120]])


We can convert Tensor into Numpy array just by simply calling `tensor.numpy()`

In [43]:
tensor_to_numpy = tensor_1.numpy()
print(type(tensor_1))
print(type(tensor_to_numpy))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


And also convert Numpy array to tensor by calling `torch.from_numpy()`

In [44]:
numpy_1 = np.arange(10)
numpy_to_tensor = torch.from_numpy(numpy_1) 
print(type(numpy_1))
print(type(numpy_to_tensor))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


Sometimes, we have to reshape our tensor to certain shape to perform calculation.
<br>To do so, torch has 2 options:

1.   `tensor.view()`
2.   `tensor.reshape()`

For `tensor.view()`, the returned tensor will share the underlying data with the original tensor, therefore making changes in the reshaped tensor will also affect with the original tensor.  `tensor.view()` could only accept contiguous tensor, if non_contigous tensor(eg: transposed tensor) was passed, error will be prompted.
<br>
<br>
For more detailed explaination, you could read it at [here](https://pytorch.org/docs/stable/tensor_view.html)

In [45]:
# The reshaped tensor will use the same storage when using tensor.view()
print("Original tensor storage location: ", tensor_1.data_ptr())
view_tensor = tensor_1.view(1,6)
print("View tensor storage location: ", view_tensor.data_ptr())
print("Reshaped: \n", view_tensor)

Original tensor storage location:  1543907307712
View tensor storage location:  1543907307712
Reshaped: 
 tensor([[1, 2, 3, 4, 8, 9]])


In [46]:
# Error will be prompted when we are trying to reshape using tensor.view() on non-contiguous tensor
# Transposed tensor will share same storage as the original tensor
transposed = tensor_1.T
print("Transposed tensor storage location: ", transposed.data_ptr())
print("Transposed: \n", transposed)

# view() with error
try:
    transposed.view(1,6)
except Exception as e:
    print("Error:")
    print(e)

Transposed tensor storage location:  1543907307712
Transposed: 
 tensor([[1, 3, 8],
        [2, 4, 9]])
Error:
view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.


In [47]:
transposed.is_contiguous()

False

If we want to use `tensor.view()`, another way to do so is simply calling `tensor.contiguous()`, which will create a new storage to convert the tensor into a contiguous tensor.

In [48]:
transposed = tensor_1.T.contiguous()
print("New transposed tensor storage location: " ,transposed.data_ptr())
print(transposed.is_contiguous())

New transposed tensor storage location:  1543907309888
True


In [49]:
t_view = transposed.view(1,6)
print(t_view)

tensor([[1, 3, 8, 2, 4, 9]])


So when we perform data modification on the reshaped tensor(t_view), the changes will be reflect on original tensor too

In [50]:
print("Before assigning: \n" ,transposed)
t_view[0,2] = 0
print("After assigning: \n",transposed)

Before assigning: 
 tensor([[1, 3, 8],
        [2, 4, 9]])
After assigning: 
 tensor([[1, 3, 0],
        [2, 4, 9]])


`tensor.reshape()` can operate on both contiguous and non-contiguous tensor. It will be a view of input if continguous input was passed, otherwise it will allocate a new memory storage to store the reshaped tensor.

In [51]:
print("Original tensor storage location: " ,tensor_1.data_ptr())
transposed = tensor_1.T
t_reshape = transposed.reshape(1,6)
print("Reshape tensor storage location: " ,t_reshape.data_ptr())
print("Reshaped: \n" ,t_reshape)

Original tensor storage location:  1543907307712
Reshape tensor storage location:  1543907311552
Reshaped: 
 tensor([[1, 3, 8, 2, 4, 9]])


In [52]:
print("Before assigning: \n",transposed)
t_reshape[0,2] = 10
print("After assigning: \n" ,transposed)

Before assigning: 
 tensor([[1, 3, 8],
        [2, 4, 9]])
After assigning: 
 tensor([[1, 3, 8],
        [2, 4, 9]])


## 1.5 Tensors on CPU and GPU  

Throughout our course we will be using PyTorch with both CPU and GPU capabilities (CUDA Toolkit), thus the need for us to show how to utilize both CPU and GPU.
<br><br>
Before we utillize the GPU, the norm is that we check if cuda is available, and declare a `torch.device("cuda:0")` for later use.<br>Notation-wise, `cuda` refers to the cuda-enabled gpu and `:0` refers to the index of the GPU. This is useful when you have multiple GPUs.

In [53]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)

cuda:0


PyTorch allows us to seamlessly move data to and from our GPU to perform computations with the following methods:
- `torch.rand((shape),device="cuda")`- this method initializes the tensor in GPU memory.
- `tensor.to("cuda")`- this method returns a copy of the tensor in GPU memory
- `tensor.cuda()`- this method returns a copy of the tensor in GPU memory

In [54]:
tensor = torch.rand((2,3,4),device=device)
print(tensor)
tensor_1 = torch.rand((2,3,4))
tensor_2 = tensor.to("cuda:0")
print(tensor_2)
tensor_3 = tensor.cuda(device)
# or just tensor.cuda() if there is only one GPU
print(tensor_3)

tensor([[[0.8761, 0.4067, 0.0178, 0.4623],
         [0.9986, 0.6126, 0.9758, 0.1552],
         [0.5249, 0.5470, 0.3420, 0.9898]],

        [[0.6732, 0.4558, 0.0051, 0.1461],
         [0.8312, 0.0735, 0.9342, 0.4310],
         [0.4204, 0.2009, 0.1191, 0.9088]]], device='cuda:0')
tensor([[[0.8761, 0.4067, 0.0178, 0.4623],
         [0.9986, 0.6126, 0.9758, 0.1552],
         [0.5249, 0.5470, 0.3420, 0.9898]],

        [[0.6732, 0.4558, 0.0051, 0.1461],
         [0.8312, 0.0735, 0.9342, 0.4310],
         [0.4204, 0.2009, 0.1191, 0.9088]]], device='cuda:0')
tensor([[[0.8761, 0.4067, 0.0178, 0.4623],
         [0.9986, 0.6126, 0.9758, 0.1552],
         [0.5249, 0.5470, 0.3420, 0.9898]],

        [[0.6732, 0.4558, 0.0051, 0.1461],
         [0.8312, 0.0735, 0.9342, 0.4310],
         [0.4204, 0.2009, 0.1191, 0.9088]]], device='cuda:0')


Notice that these tensors are **stored in separate devices.** Hence, both separate tensors in respectively **CPU and GPU are not capable of performing operations with each other**.

In [55]:
try:
    print(tensor_1+tensor_2)
except Exception as e:
    print(e)

Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!


To check the type of device that the tensor is in, simply use `tensor.device`

In [56]:
print(tensor_1.device)
print(tensor_2.device)

cpu
cuda:0


# Exercise

**_TASK_**: Initialize a tensor of random integers ranging from 0-100 with **dimensions(5,8,7)**

In [2]:
tensor = torch.randint(0,100,(5,8,7))
print(tensor)

tensor([[[44, 39, 33, 60, 63, 79, 27],
         [ 3, 97, 83,  1, 66, 56, 99],
         [78, 76, 56, 68, 94, 33, 26],
         [19, 91, 54, 24, 41, 69, 69],
         [49, 80, 81, 12, 63, 60, 95],
         [85, 22, 99, 11, 88, 78, 43],
         [96, 89, 71, 57, 83, 95, 82],
         [71, 40, 69, 73, 41, 11, 80]],

        [[ 3,  6, 76, 27, 99, 26, 63],
         [74, 75,  0, 18, 32, 68, 12],
         [77, 45, 10, 80, 48, 21, 19],
         [16, 81, 90, 82, 19, 44, 33],
         [69, 63,  9, 33, 19, 78, 35],
         [83, 22, 58, 35, 16, 46, 35],
         [77, 12,  5, 46, 56, 15, 84],
         [50,  8, 71, 47,  8, 75, 84]],

        [[84, 48, 44, 34, 19, 60,  7],
         [14, 75, 63, 13, 57, 33, 20],
         [49, 89, 93, 11, 28, 31, 77],
         [58, 84,  1, 70, 84, 90, 84],
         [69, 27, 70, 10, 41, 84, 19],
         [69,  5, 99, 72, 62, 42, 71],
         [14, 39, 71, 11, 50, 73, 30],
         [66, 87, 26, 19, 71,  6, 94]],

        [[91, 20, 85, 42, 75, 18,  1],
         [18, 61, 1

#### Expected Output :
```
tensor([[[44, 39, 33, 60, 63, 79, 27],
         [ 3, 97, 83,  1, 66, 56, 99],
         [78, 76, 56, 68, 94, 33, 26],
         [19, 91, 54, 24, 41, 69, 69],
         [49, 80, 81, 12, 63, 60, 95],
         [85, 22, 99, 11, 88, 78, 43],
         [96, 89, 71, 57, 83, 95, 82],
         [71, 40, 69, 73, 41, 11, 80]],

        [[ 3,  6, 76, 27, 99, 26, 63],
         [74, 75,  0, 18, 32, 68, 12],
         [77, 45, 10, 80, 48, 21, 19],
         [16, 81, 90, 82, 19, 44, 33],
         [69, 63,  9, 33, 19, 78, 35],
         [83, 22, 58, 35, 16, 46, 35],
         [77, 12,  5, 46, 56, 15, 84],
         [50,  8, 71, 47,  8, 75, 84]],

        [[84, 48, 44, 34, 19, 60,  7],
         [14, 75, 63, 13, 57, 33, 20],
         [49, 89, 93, 11, 28, 31, 77],
         [58, 84,  1, 70, 84, 90, 84],
         [69, 27, 70, 10, 41, 84, 19],
         [69,  5, 99, 72, 62, 42, 71],
         [14, 39, 71, 11, 50, 73, 30],
         [66, 87, 26, 19, 71,  6, 94]],

        [[91, 20, 85, 42, 75, 18,  1],
         [18, 61, 12, 78, 50, 43, 28],
         [39, 82,  7, 60, 88, 78, 96],
         [98, 15, 18, 66, 95, 72, 84],
         [12, 77, 42, 84, 69, 18, 95],
         [ 6, 74, 43, 33, 64,  0, 12],
         [15, 51, 12, 78,  2, 44,  8],
         [23, 36, 45, 78, 68, 40, 15]],

        [[21,  3, 80, 18, 21, 41, 81],
         [47, 32, 32, 92, 93, 33, 86],
         [37, 88, 20, 65, 30, 13, 65],
         [95, 33, 96, 52, 32, 35, 75],
         [69, 74, 73,  3, 57, 43, 48],
         [20, 47, 45, 38, 32, 94, 67],
         [43, 22, 55, 45, 93, 69, 91],
         [78, 40, 96, 37, 64, 67, 86]]])
```

**_TASK_**: Slice out part of the tensor with dimensions $(0->4,3->6,1->6)$ and name it `slice_1`

In [3]:
slice_1 = tensor[0:5,3:7,1:7]
print(slice_1)

tensor([[[91, 54, 24, 41, 69, 69],
         [80, 81, 12, 63, 60, 95],
         [22, 99, 11, 88, 78, 43],
         [89, 71, 57, 83, 95, 82]],

        [[81, 90, 82, 19, 44, 33],
         [63,  9, 33, 19, 78, 35],
         [22, 58, 35, 16, 46, 35],
         [12,  5, 46, 56, 15, 84]],

        [[84,  1, 70, 84, 90, 84],
         [27, 70, 10, 41, 84, 19],
         [ 5, 99, 72, 62, 42, 71],
         [39, 71, 11, 50, 73, 30]],

        [[15, 18, 66, 95, 72, 84],
         [77, 42, 84, 69, 18, 95],
         [74, 43, 33, 64,  0, 12],
         [51, 12, 78,  2, 44,  8]],

        [[33, 96, 52, 32, 35, 75],
         [74, 73,  3, 57, 43, 48],
         [47, 45, 38, 32, 94, 67],
         [22, 55, 45, 93, 69, 91]]])


#### Expected Output :
```
tensor([[[91, 54, 24, 41, 69, 69],
         [80, 81, 12, 63, 60, 95],
         [22, 99, 11, 88, 78, 43],
         [89, 71, 57, 83, 95, 82]],

        [[81, 90, 82, 19, 44, 33],
         [63,  9, 33, 19, 78, 35],
         [22, 58, 35, 16, 46, 35],
         [12,  5, 46, 56, 15, 84]],

        [[84,  1, 70, 84, 90, 84],
         [27, 70, 10, 41, 84, 19],
         [ 5, 99, 72, 62, 42, 71],
         [39, 71, 11, 50, 73, 30]],

        [[15, 18, 66, 95, 72, 84],
         [77, 42, 84, 69, 18, 95],
         [74, 43, 33, 64,  0, 12],
         [51, 12, 78,  2, 44,  8]],

        [[33, 96, 52, 32, 35, 75],
         [74, 73,  3, 57, 43, 48],
         [47, 45, 38, 32, 94, 67],
         [22, 55, 45, 93, 69, 91]]])
```

**_TASK_**: Produce 5 chunks of tensors where $dim = 0$ from `slice_1` and put it in a list: `list_1`

In [4]:
list_1 = slice_1.chunk(5)
for chunk in list_1:
    print(chunk)

tensor([[[91, 54, 24, 41, 69, 69],
         [80, 81, 12, 63, 60, 95],
         [22, 99, 11, 88, 78, 43],
         [89, 71, 57, 83, 95, 82]]])
tensor([[[81, 90, 82, 19, 44, 33],
         [63,  9, 33, 19, 78, 35],
         [22, 58, 35, 16, 46, 35],
         [12,  5, 46, 56, 15, 84]]])
tensor([[[84,  1, 70, 84, 90, 84],
         [27, 70, 10, 41, 84, 19],
         [ 5, 99, 72, 62, 42, 71],
         [39, 71, 11, 50, 73, 30]]])
tensor([[[15, 18, 66, 95, 72, 84],
         [77, 42, 84, 69, 18, 95],
         [74, 43, 33, 64,  0, 12],
         [51, 12, 78,  2, 44,  8]]])
tensor([[[33, 96, 52, 32, 35, 75],
         [74, 73,  3, 57, 43, 48],
         [47, 45, 38, 32, 94, 67],
         [22, 55, 45, 93, 69, 91]]])


#### Expected Output :
```
tensor([[[91, 54, 24, 41, 69, 69],
         [80, 81, 12, 63, 60, 95],
         [22, 99, 11, 88, 78, 43],
         [89, 71, 57, 83, 95, 82]]])
tensor([[[81, 90, 82, 19, 44, 33],
         [63,  9, 33, 19, 78, 35],
         [22, 58, 35, 16, 46, 35],
         [12,  5, 46, 56, 15, 84]]])
tensor([[[84,  1, 70, 84, 90, 84],
         [27, 70, 10, 41, 84, 19],
         [ 5, 99, 72, 62, 42, 71],
         [39, 71, 11, 50, 73, 30]]])
tensor([[[15, 18, 66, 95, 72, 84],
         [77, 42, 84, 69, 18, 95],
         [74, 43, 33, 64,  0, 12],
         [51, 12, 78,  2, 44,  8]]])
tensor([[[33, 96, 52, 32, 35, 75],
         [74, 73,  3, 57, 43, 48],
         [47, 45, 38, 32, 94, 67],
         [22, 55, 45, 93, 69, 91]]])
```

**_TASK_**: Concatenate the first and third chunk together at dimension 2 and name it `cat_1`

In [5]:
cat_1 = torch.cat((list_1[0],list_1[2]),2)
print(cat_1)

tensor([[[91, 54, 24, 41, 69, 69, 84,  1, 70, 84, 90, 84],
         [80, 81, 12, 63, 60, 95, 27, 70, 10, 41, 84, 19],
         [22, 99, 11, 88, 78, 43,  5, 99, 72, 62, 42, 71],
         [89, 71, 57, 83, 95, 82, 39, 71, 11, 50, 73, 30]]])


#### Expected Output :
```
tensor([[[91, 54, 24, 41, 69, 69, 84,  1, 70, 84, 90, 84],
         [80, 81, 12, 63, 60, 95, 27, 70, 10, 41, 84, 19],
         [22, 99, 11, 88, 78, 43,  5, 99, 72, 62, 42, 71],
         [89, 71, 57, 83, 95, 82, 39, 71, 11, 50, 73, 30]]])
```

**_TASK_**: Add `tensor_1` and `tensor_2` five times and store the result in the same storage location of `tensor_2`.

In [6]:
tensor_1 = torch.tensor([1, 0, -1, -1, 0, 1])
tensor_2 = torch.tensor([[21, 45, 68, 32, 1, 0],
                        [93, 32, 33, 20, 5, 72]])
tensor_ans = torch.empty(0)
tensor_ans = tensor_2.add_(tensor_1.mul(5))

In [7]:
loc_tensor_1 = tensor_1.data_ptr()
loc_tensor_2 = tensor_2.data_ptr()
loc_tensor_ans = tensor_ans.data_ptr()
print("tensor_ans: \n" + str(tensor_ans))
print("\nIs tensor storage location of tensor_ans same as tensor storage location of tensor_2: " + str(loc_tensor_ans == loc_tensor_2))

tensor_ans: 
tensor([[26, 45, 63, 27,  1,  5],
        [98, 32, 28, 15,  5, 77]])

Is tensor storage location of tensor_ans same as tensor storage location of tensor_2: True


#### Expected Output :
```
tensor_ans: 
tensor([[26, 45, 63, 27,  1,  5],
        [98, 32, 28, 15,  5, 77]])

Is tensor storage location of tensor_ans same as tensor storage location of tensor_2: True
```

**_TASK_**: Lets say right now we want to have **two** 8-bit RGB image with the size of 228 x 228, try to randomly initialize the tensors with the detail given 
(height, width, channel).

*Hint* : Use `torch.randint`

In [8]:
# Intialize the tensors
tensor_1 = torch.randint(0,256,(228,228,3))
tensor_2 = torch.randint(0,256,(228,228,3))

print("First 10 values for tensor 1 : ", tensor_1[0:10,0,0])
print("First 10 values for tensor 2 : ", tensor_2[0:10,0,0])

First 10 values for tensor 1 :  tensor([239, 194, 220, 114, 159,  42, 211, 211, 207, 222])
First 10 values for tensor 2 :  tensor([111, 155,  17, 170, 220, 237,  19,  18, 127, 185])


#### Expected Output :
``` 
First 10 values for tensor 1 :  tensor([239, 194, 220, 114, 159,  42, 211, 211, 207, 222])
First 10 values for tensor 2 :  tensor([111, 155,  17, 170, 220, 237,  19,  18, 127, 185])
```

It is impossible to perform matric multiplication on a 3D tensor, therefore we have to reshape it into a 2D tensor.

**_TASK_**: It this case, we would like to change the order of dimension of the tensor to shape$(channel, height, width)$ so that when we reshape, it would become $(channel, height \times width)$

*hint* : Use `tensor.permute`

In [9]:
# Change the order of the tensor dimension
tensor_1 = tensor_1.permute(2,0,1)
tensor_2 = tensor_2.permute(2,0,1)

print(tensor_1.shape)
print(tensor_2.shape)

torch.Size([3, 228, 228])
torch.Size([3, 228, 228])


#### Expected Output :
``` 
torch.Size([3, 228, 228])
torch.Size([3, 228, 228])
```

**_TASK_**: Perform reshape on the tensor

*hint* : Use `tensor.view`

In [10]:
# Reshape the tensor
tensor_1 = tensor_1.view(3,-1)
tensor_2 = tensor_1.view(3,-1)

print(tensor_1.shape)
print(tensor_1.shape)

torch.Size([3, 51984])
torch.Size([3, 51984])


#### Expected Output :
``` 
torch.Size([3, 51984])
torch.Size([3, 51984])
```

**_TASK_**: Perform matric multiplication between the tensors, take note that you might need to transpose to match the shape (3x3)

In [11]:
# Perform matric multiplication
tensor_mm = torch.mm(tensor_1,tensor_2.t())

print(tensor_mm)

tensor([[1138473070,  850800576,  852055266],
        [ 850800576, 1130950560,  846511247],
        [ 852055266,  846511247, 1131113481]])


#### Expected Output :
``` 
tensor([[845716185, 842557652, 845981041],
        [853949685, 846237767, 849568376],
        [848178623, 842627404, 849479321]])
```

**_TASK_**: Initialize a **gpu device.** Then, initialize a random tensor with any size and store it in the device.

In [12]:
# initialize cuda device
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
tensor = torch.rand((2,3,6), device=device)
print(tensor)

tensor([[[0.3990, 0.5167, 0.0249, 0.9401, 0.9459, 0.7967],
         [0.4150, 0.8203, 0.2290, 0.9096, 0.1183, 0.0752],
         [0.4092, 0.9601, 0.2093, 0.1940, 0.8909, 0.4387]],

        [[0.3570, 0.5454, 0.8299, 0.2099, 0.7684, 0.4290],
         [0.2117, 0.6606, 0.1654, 0.4250, 0.9927, 0.6964],
         [0.2472, 0.7028, 0.7494, 0.9303, 0.0494, 0.0750]]], device='cuda:0')


#### Expected Output :
``` 
torch.Size([3, 51984])
torch.Size([3, 51984])
```