# Tensors

## 1.1 Introduction to Tensors

**Tensors** is the fundamental data structure, a multidimensional array in PyTorch. It is metaphorical relatable to the numpy array of Numpy. The difference between the two is that tensors are available in two modes: `CPU and GPU`. We will touch this mentioned feature at the end of this tutorial.
<br>
<br>
There are a few ways to build a tensor:
- `torch.arange()`
- `torch.ones()`
- `torch.zeros()`
- `torch.rand()`
- `torch.randint()`
- `torch.fromnumpy()`

In [1]:
import torch
import numpy as np

`torch.arange(n,m)` returns a 1-dimensional tensor with values ranging from $n$ to $m-1$ 

In [2]:
tensor = torch.arange(0,20)
print(tensor)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])


`torch.ones(dim_0,dim_1,...,dim_n)` returns a tensor of ones of the shape $ dim_{0} \times dim_{1} \times...\times dim_{n} $

In [3]:
print(torch.ones(3,4,6))

tensor([[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]])


`torch.zeros(dim_0,dim_1,...,dim_n)` returns a tensor of zeros of the shape $ dim_{0} \times dim_{1} \times...\times dim_{n} $

In [4]:
print(torch.zeros(3,4,6))

tensor([[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]])


`torch.rand(dim_0, dim_1,...,dim_m)` returns a tensor filled with random floats ranging from $0$ to $1$.

In [5]:
print(torch.rand(3,4,6))

tensor([[[0.6513, 0.5194, 0.5412, 0.6894, 0.9348, 0.2343],
         [0.2486, 0.5848, 0.2779, 0.3646, 0.8814, 0.0133],
         [0.3029, 0.8827, 0.6321, 0.0930, 0.1690, 0.6725],
         [0.7703, 0.7282, 0.3703, 0.1304, 0.1142, 0.9953]],

        [[0.3738, 0.2207, 0.1401, 0.5189, 0.2542, 0.2804],
         [0.0168, 0.2070, 0.6998, 0.3570, 0.6767, 0.0627],
         [0.5908, 0.5445, 0.2538, 0.6304, 0.3765, 0.0335],
         [0.1378, 0.1654, 0.1054, 0.6410, 0.9823, 0.2457]],

        [[0.3281, 0.3186, 0.5319, 0.0768, 0.1083, 0.4254],
         [0.6244, 0.9045, 0.5733, 0.3466, 0.6029, 0.0899],
         [0.8688, 0.3751, 0.4406, 0.6200, 0.4315, 0.7935],
         [0.4607, 0.9507, 0.2381, 0.3102, 0.3906, 0.6890]]])


## 1.2 Mathematical Operations on Tensors

### Basic Mathematical Operations

First of all, let's initialize two tensors which are $t_1$ and $t_2$.

In [6]:
t1 = torch.rand(3,2)
t2 = torch.rand(3,2)
print("t1: \n"+str(t1))
print("t2: \n"+str(t2))

t1: 
tensor([[0.7775, 0.4975],
        [0.4197, 0.1914],
        [0.5642, 0.9337]])
t2: 
tensor([[0.9274, 0.2700],
        [0.1267, 0.9101],
        [0.7749, 0.0797]])


#### Addition

In [7]:
tensorAdd = torch.add(t1, t2)
print("Addition of t1 and t2: \n" + str(tensorAdd))

Addition of t1 and t2: 
tensor([[1.7049, 0.7674],
        [0.5464, 1.1015],
        [1.3391, 1.0135]])


In [8]:
tensorAdd_2 = t1 + t2
print("Addition of t1 and t2 using '+' operator:\n"+str(tensorAdd_2))

Addition of t1 and t2 using '+' operator:
tensor([[1.7049, 0.7674],
        [0.5464, 1.1015],
        [1.3391, 1.0135]])


#### Subtraction

In [9]:
tensorSub = torch.sub(t1, t2)
print("Subtraction of t1 and t2: \n" + str(tensorSub))

Subtraction of t1 and t2: 
tensor([[-0.1499,  0.2275],
        [ 0.2930, -0.7188],
        [-0.2107,  0.8540]])


In [10]:
tensorSub_2 = t1 - t2
print("Addition of t1 and t2 using '-' operator:\n"+str(tensorSub_2))

Addition of t1 and t2 using '-' operator:
tensor([[-0.1499,  0.2275],
        [ 0.2930, -0.7188],
        [-0.2107,  0.8540]])


#### Multiplication

`torch.mul(t1, t2)` - element-wise multiplication and scalar multiplication  <br /> 
`torch.mm(t1, t2)` - matrix multiplication

Element-wise multiplication required two tensors with same size. 
>Lets say tensor $t_1$ has $n \times m$ dimension, then tensor $t_2$ should also have $n \times m$ dimension in order to perform element-wise multiplication. <br>The tensor size of element-wise multiplication will be same as the tensor element size $n \times m$.

In [11]:
print("Size of t1: " + str(t1.shape))
print("Size of t2: " + str(t2.shape))
tensorMul = torch.mul(t1, t2)
print("\nElement-wise multiplication of t1 and t2: \n" + str(tensorMul))
print("Size of tensorMul: " + str(tensorMul.shape))

Size of t1: torch.Size([3, 2])
Size of t2: torch.Size([3, 2])

Element-wise multiplication of t1 and t2: 
tensor([[0.7210, 0.1343],
        [0.0532, 0.1742],
        [0.4372, 0.0744]])
Size of tensorMul: torch.Size([3, 2])


In [12]:
print("Size of t1: " + str(t1.shape))
print("Size of t2: " + str(t2.shape))
tensorMul_2 = t1 * t2
print("\nElement-wise multiplication of t1 and t2 using '*' operator: \n" + str(tensorMul_2))
print("Size of tensorMul_2: " + str(tensorMul_2.shape))

Size of t1: torch.Size([3, 2])
Size of t2: torch.Size([3, 2])

Element-wise multiplication of t1 and t2 using '*' operator: 
tensor([[0.7210, 0.1343],
        [0.0532, 0.1742],
        [0.4372, 0.0744]])
Size of tensorMul_2: torch.Size([3, 2])


In [13]:
# Matrix multiplication
mat_1 = torch.rand(3,3)
mat_2 = torch.rand(3,3)
print(mat_1.mm(mat_2))

tensor([[2.0605, 1.5914, 1.4161],
        [0.8283, 0.6934, 0.6511],
        [1.2302, 0.7178, 0.5959]])


Matrix multiplication requires two tensors that fulfills the following conditions, where:  
>Let's say tensor $t_1$ has $n \times m$ dimension, then tensor $t_2$ must has $m \times p$ dimension in order to perform matrix multiplication.<br>
The resulting tensor size of matrix multiplication between $t_1$ and $t_2$ will be $n \times p$.

In [14]:
print("Size of t1: " + str(t1.shape))
print("Size of t2: " + str(t2.shape))
try:
    tensorMM = torch.mm(t1, t2)
    print("\nMatrix multiplication of t1 and t2: \n" + str(tensorMM))
    print("Size of tensorMM: " + str(tensorMM.shape))
except Exception as e:
    print(e)

Size of t1: torch.Size([3, 2])
Size of t2: torch.Size([3, 2])
size mismatch, m1: [3 x 2], m2: [3 x 2] at ..\aten\src\TH/generic/THTensorMath.cpp:41


Error above shows `size mismatch`, because $t_2$ size does not match. In order to perform matrix multiplication, let's transpose $t_2$ using `t2.T`.

In [15]:
t2_T = t2.T
print("Size of t1: " + str(t1.shape))
print("Size of t2: " + str(t2_T.shape))
tensorMM = torch.mm(t1, t2_T)
print("\nMatrix multiplication of t1 and t2: \n" + str(tensorMM))
print("Size of tensorMM: " + str(tensorMM.shape))

Size of t1: torch.Size([3, 2])
Size of t2: torch.Size([2, 3])

Matrix multiplication of t1 and t2: 
tensor([[0.8554, 0.5513, 0.6422],
        [0.4409, 0.2273, 0.3405],
        [0.7753, 0.9213, 0.5116]])
Size of tensorMM: torch.Size([3, 3])


#### Division

Like element-wise multiplication, division between matrices requires both matrices be of the same size and results in a tensor of the same size as well.

In [16]:
print("Size of t1: " + str(t1.shape))
print("Size of t2: " + str(t2.shape))
tensorDiv = torch.div(t1, t2)
print("\nElement-wise division of t1 and t2: \n" + str(tensorDiv))
print("Size of tensorDiv: " + str(tensorDiv.shape))

Size of t1: torch.Size([3, 2])
Size of t2: torch.Size([3, 2])

Element-wise division of t1 and t2: 
tensor([[ 0.8384,  1.8426],
        [ 3.3126,  0.2102],
        [ 0.7281, 11.7109]])
Size of tensorDiv: torch.Size([3, 2])


In [17]:
tensorDiv_1 = t1 / t2
print("Element-wise division of t1 and t2 with '/' operator: \n" + str(tensorDiv_1))
print("Size of tensorDiv: " + str(tensorDiv_1.shape))

Element-wise division of t1 and t2 with '/' operator: 
tensor([[ 0.8384,  1.8426],
        [ 3.3126,  0.2102],
        [ 0.7281, 11.7109]])
Size of tensorDiv: torch.Size([3, 2])


#### Exponential

For every element x in the tensor, apply exponential function $e^{x}$

In [18]:
tensorExp = torch.exp(t1)
print("Exponential of t1: \n" + str(tensorExp))

Exponential of t1: 
tensor([[2.1760, 1.6445],
        [1.5215, 1.2109],
        [1.7580, 2.5440]])


#### Sigmoid

For every element x in the tensor, apply sigmoid function $\frac{1}{1+e^{-x}}$


In [19]:
tensorSig = torch.sigmoid(t1)
print("Sigmoid of t1: \n" + str(tensorSig))

Sigmoid of t1: 
tensor([[0.6851, 0.6219],
        [0.6034, 0.5477],
        [0.6374, 0.7178]])


### Reduction Operations

In [20]:
t1 = torch.rand(3,2)
t2 = torch.rand(3,2)
print("t1: \n"+str(t1))
print("t2: \n"+str(t2))

t1: 
tensor([[0.5166, 0.8595],
        [0.6398, 0.5927],
        [0.3385, 0.0198]])
t2: 
tensor([[0.7197, 0.1429],
        [0.6216, 0.4493],
        [0.7102, 0.3071]])


#### Argmax

Returns the indices of the maximum value of all elements in the input tensor.

If no axis is specified, it will flatten the tensor and return the index of maximum value of all elements in the tensor.

In [21]:
torch.argmax(t1)

tensor(1)

`axis=0` will return the indices of the maximum value of each elements in each coloumns in the tensor.

In [22]:
torch.argmax(t1, axis=0)

tensor([1, 0])

`axis=1` will return the indices of the maximum value of each elements in each rows in the tensor.

In [23]:
torch.argmax(t1, axis=1)

tensor([1, 0, 0])

#### Sum

Returns the sum of all elements in the input tensor.

In [24]:
tensor1Sum = torch.sum(t1)
print("Sum of the tensor t1: " + str(float(tensor1Sum)))

Sum of the tensor t1: 2.966923713684082


In [25]:
tensor2Sum = torch.sum(t2)
print("Sum of the tensor t2: " + str(float(tensor2Sum)))

Sum of the tensor t2: 2.9507791996002197


### Normal Operations vs Inplace Operations

We first initialize $t_1$ and $t_2$ tensor and check their tensor storage location. We will perform both normal and inplace additions and assign it to a variable $t_3$ and later on compare their values to see their differences.

In [26]:
t1 = torch.tensor([1,1,1])
t2 = torch.tensor([2,2,2])
t3 = t1.add(t2)
print("Normal Operation:")
print("t1: \n"+str(t1))
print("t2: \n"+str(t2))
print("t3: \n"+str(t3))

print("\nTensor storage location of t1: " + str(t1.data_ptr()))
print("Tensor storage location of t2: " + str(t2.data_ptr()))
print("Tensor storage location of t3: " + str(t3.data_ptr()))

Normal Operation:
t1: 
tensor([1, 1, 1])
t2: 
tensor([2, 2, 2])
t3: 
tensor([3, 3, 3])

Tensor storage location of t1: 2293186696512
Tensor storage location of t2: 2293186696640
Tensor storage location of t3: 2293186695808


In [27]:
t1 = torch.tensor([1,1,1])
t2 = torch.tensor([2,2,2])
t3 = t1.add_(t2)
print("In-place Operation:")
print("t1: \n"+str(t1))
print("t2: \n"+str(t2))
print("t3: \n"+str(t3))

print("\nTensor storage location of t1: " + str(t1.data_ptr()))
print("Tensor storage location of t2: " + str(t2.data_ptr()))
print("Tensor storage location of t3: " + str(t3.data_ptr()))

In-place Operation:
t1: 
tensor([3, 3, 3])
t2: 
tensor([2, 2, 2])
t3: 
tensor([3, 3, 3])

Tensor storage location of t1: 2293186691904
Tensor storage location of t2: 2293186696512
Tensor storage location of t3: 2293186691904


Notice that in normal operations, the result of the operation is only assigned to $t_3$.<br> 
Whereas in in-place operations, the result of the operation is directly stored in the original tensor where the in-place operations are called on. 

In this case, we called `t1.add_()`, which means the data in $t_1$ tensor will change into the result of the addition.

## 1.3 Tensor Indexing, Slicing, Joining, Mutating

### Indexing and Slicing

Tensor indexing and slicing is similar to that of `numpy`:<br>

>To get the element with indices $(x,y,z)$ in tensor $a$:<br> 
`element = a[x,y,z]`

>To slice a part of the tensor $a$ in range $(x_1\Rightarrow x_2,y_1\Rightarrow y_2,z_1\Rightarrow z_2)$:<br> 
`slice = a[x_1:x_2+1,y_1:y_2+1,z_1:z_2+1]`

In [28]:
# Indexing and Slicing
t_1 = torch.arange(0,24).reshape(-1,6)
print(t_1)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])


<img src= ../data/indexing.png width=300 height=300>

Let's try to get number $7$ out of the $t_1$.<br>
$7$ will have the index $(1,1)$

In [29]:
t_1[1,1]

tensor(7)

In [30]:
print(int(t_1[1,1]))

7


<img src= ../data/slicing.png width=300 height=300>

Let's try to slice out the above portion from $t_1$<br>
This will have index range of $(0\Rightarrow 2,2\Rightarrow 4)$

In [31]:
print(t_1[:3,2:5])

tensor([[ 2,  3,  4],
        [ 8,  9, 10],
        [14, 15, 16]])


### Joining and Splitting

Just like in Numpy arrays, PyTorch tensors are able to join with each other. There are a few tensor methods that allow joining:
- `torch.cat((tensor_1,tensor_2), ndim)`
- `torch.stack((tensor_1,tensor_2), ndim)`

For example, let's join $t_1$ and $t_2$ at all of their dimensions respectively.

In [32]:
# Joining
# tensor.cat()
t_1 = torch.ones((2,2,7))
t_2 = torch.zeros((2,2,7))
print("t_1:",t_1,sep="\n")
print("t_2:",t_2,sep="\n")

t_1:
tensor([[[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]]])
t_2:
tensor([[[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]]])


In [33]:
join_0 = torch.cat((t_1,t_2),0)
print("Concatenation at dimension 0: \n"+ str(join_0), end="\n\n")
print(join_0.shape)

Concatenation at dimension 0: 
tensor([[[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]]])

torch.Size([4, 2, 7])


In [34]:
join_1 = torch.cat((t_1,t_2),1)
print("Concatenation at dimension 1: \n"+ str(join_1), end="\n\n")
print(join_1.shape)

Concatenation at dimension 1: 
tensor([[[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]]])

torch.Size([2, 4, 7])


In [35]:
join_2 = torch.cat((t_1,t_2),2)
print("Concatenation at dimension 2: \n"+ str(join_2), end="\n\n")
print(join_2.shape)

Concatenation at dimension 2: 
tensor([[[1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.]],

        [[1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.]]])

torch.Size([2, 2, 14])


><i>Note:</i> During concatenation using `torch.cat()`, all of the dimensions except the dimension that is subject to concatenation have to be of the same size 
<br><br> For example, if we have tensor $a$ and $b$, with shape $(3,2,4)$ and $(3,1,4)$ respectively, concatenation on dimension 1 is only valid 

In [36]:
# Correct concatenation
a = torch.ones((3,2,4))
b = torch.zeros((3,1,4))
print(torch.cat((a,b),1))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [0., 0., 0., 0.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [0., 0., 0., 0.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [0., 0., 0., 0.]]])


In [37]:
# Error in concatenation
try:
    print(torch.cat((a,b),0))
except Exception as e:
    print(e)

Sizes of tensors must match except in dimension 0. Got 2 and 1 in dimension 1 (The offending index is 1)


We could also use `torch.stack()` to join two tensors. This function will stack two tensors on a new dimension with the condition that **both tensors are of the same shape**.

In [38]:
c = torch.zeros((3,2,4))
print(torch.stack((a,c)))

tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]]]])


PyTorch also provides ways to split up tensors on dimension specified, namely:
- `torch.split(tensor, split_size_or_section_size, n_dim)`
- `torch.chunk(tensor, number_of_chunks, n_dim)`

In [39]:
tensor = torch.arange(0,30).reshape(3,2,5)
print("original tensor: \n"+ str(tensor))

original tensor: 
tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]])


In [40]:
# splitting with chunk size
splits= torch.split(tensor,1,0)
for i,split in enumerate(splits):
    print(f"Split {i+1}:")
    print(split)

Split 1:
tensor([[[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]])
Split 2:
tensor([[[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]])
Split 3:
tensor([[[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]])


In [41]:
# splitting with section_size list [1,2,2]
section1, section2 = torch.split(tensor,[1,2],0)
print("section 1:\n"+str(section1), end="\n\n")
print("section 2:\n"+str(section2), end="\n\n")

section 1:
tensor([[[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]])

section 2:
tensor([[[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]])



In [42]:
# chunking a tensor into two
split1, split2 = torch.chunk(tensor,2,0)
print("chunk1: \n"+str(split1), end="\n\n")
print("chunk2: \n"+str(split2), end="\n\n")

chunk1: 
tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]])

chunk2: 
tensor([[[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]])



### Mutating
There are three main parts in tensor mutating:
1. Transposing
2. Squeezing
3. Unsqueezing

**Transposing** 
<br>Transposing could be performed through 3 ways:
- `torch.t() or tensor.t()`            - Only workable on 2_d tensors
- `tensor.T`                           - Returns the tensors with all its dimensions reversed $(1,2,4)\rightarrow(4,2,1)$
- `torch.transpose(tensor, dim_0, dim_1)`- Performs transpose on any two dimensions specified

In [43]:
tensor_2d = torch.arange(0,30).reshape(5,6)
tensor_3d = tensor_2d.reshape(2,5,3)

In [44]:
print(torch.t(tensor_2d))
print(tensor_2d.t())

tensor([[ 0,  6, 12, 18, 24],
        [ 1,  7, 13, 19, 25],
        [ 2,  8, 14, 20, 26],
        [ 3,  9, 15, 21, 27],
        [ 4, 10, 16, 22, 28],
        [ 5, 11, 17, 23, 29]])
tensor([[ 0,  6, 12, 18, 24],
        [ 1,  7, 13, 19, 25],
        [ 2,  8, 14, 20, 26],
        [ 3,  9, 15, 21, 27],
        [ 4, 10, 16, 22, 28],
        [ 5, 11, 17, 23, 29]])


In [45]:
print(tensor_3d.T)
print(tensor_3d.shape)

tensor([[[ 0, 15],
         [ 3, 18],
         [ 6, 21],
         [ 9, 24],
         [12, 27]],

        [[ 1, 16],
         [ 4, 19],
         [ 7, 22],
         [10, 25],
         [13, 28]],

        [[ 2, 17],
         [ 5, 20],
         [ 8, 23],
         [11, 26],
         [14, 29]]])
torch.Size([2, 5, 3])


In [46]:
print(torch.transpose(tensor_3d, 2, 1))
print(torch.transpose(tensor_3d, 2, 1).shape)

tensor([[[ 0,  3,  6,  9, 12],
         [ 1,  4,  7, 10, 13],
         [ 2,  5,  8, 11, 14]],

        [[15, 18, 21, 24, 27],
         [16, 19, 22, 25, 28],
         [17, 20, 23, 26, 29]]])
torch.Size([2, 3, 5])


**Squeezing**
<br>Just like what the name suggests, squeezing helps to remove redundant dimensions with value of one. The function is as follows:

`torch.squeeze(tensor, dim)`

The function **removes all dimensions with value 1** if no dimension is specified.

In [47]:
tensor = torch.arange(0,20).reshape(1,5,2,1,2)
print("Shape before squeezing: ")
print(tensor.shape)
tensor_squeezed = torch.squeeze(tensor)
print("Shape after squeezing: ")
print(tensor_squeezed.shape)

Shape before squeezing: 
torch.Size([1, 5, 2, 1, 2])
Shape after squeezing: 
torch.Size([5, 2, 2])


In [48]:
# squeezing only dimension 3
tensor_squeezed = torch.squeeze(tensor,3)
print("Shape before squeezing: ")
print(tensor.shape)
print("Shape after squeezing dimension 3: ")
print(tensor_squeezed.shape)

Shape before squeezing: 
torch.Size([1, 5, 2, 1, 2])
Shape after squeezing dimension 3: 
torch.Size([1, 5, 2, 2])


**Unsqueeze**
<br>Sometimes we would like our tensor to match a certain dimension so that we could perform matrix operations like broadcasting. In this case we would like our **tensors to be padded with extra dimensions.**
<br> What we could do is to "unsqueeze" the matrix. 
- `torch.unsqueeze(tensor,dim)`
- `tensor.unsqueeze(dim)`
- `tensor.unsqueeze_(dim)`- inplace-operator

In [49]:
tensor = torch.arange(0,10)
print("Shape before unsqueeze:")
print(tensor.shape)
tensor.unsqueeze_(0)
print("Shape after unsqueeze:")
print(tensor.shape)

Shape before unsqueeze:
torch.Size([10])
Shape after unsqueeze:
torch.Size([1, 10])


## 1.4 Tensor objects methods

There are a lot of useful methods provided by tensor objects. In this section, we will provide some examples on commonly used tensor object methods in deep learning.
<br>
If you wish to know more on tensor object methods, you can access it at [here](https://pytorch.org/docs/stable/tensors.html)

<b>`tensor.flatten()`</b>

- reduces tensor of any dimension into a one dimensional tensor.

In [50]:
# Initializing tensor
tensor_1 = torch.tensor([[1,2], [3,4], [8,9]])
tensor_2 = torch.tensor([[5,6], [7,8]])
print("Tensor 1: \n", tensor_1)
print("Tensor 2: \n", tensor_2)

# We can flatten the tensor into single dimension by just calling tensor.flatten() 
flat = tensor_1.flatten()
print(flat)

Tensor 1: 
 tensor([[1, 2],
        [3, 4],
        [8, 9]])
Tensor 2: 
 tensor([[5, 6],
        [7, 8]])
tensor([1, 2, 3, 4, 8, 9])


<b>`tensor.mm()`</b>
- performs matrix multiplication.

In [51]:
tensor_mm = tensor_1.mm(tensor_2)
print(tensor_mm)

tensor([[ 19,  22],
        [ 43,  50],
        [103, 120]])
tensor([[ 19,  22],
        [ 43,  50],
        [103, 120]])


<b>`tensor.numpy()`</b>
- convert tensors into numpy arrays

In [52]:
tensor_to_numpy = tensor_1.numpy()
print(type(tensor_1))
print(type(tensor_to_numpy))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


<b>`torch.from_numpy()`</b>
- convert numpy arrays into tensors

In [53]:
numpy_1 = np.arange(10)
numpy_to_tensor = torch.from_numpy(numpy_1) 
print(type(numpy_1))
print(type(numpy_to_tensor))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


Sometimes, we have to reshape our tensor to certain shape to perform calculation.
<br>To do so, torch has 2 options:

1.   <b>`tensor.view()`
2.   `tensor.reshape()`</b>


This `tensor.view()` function returns a tensor with a new shape but **_shares the same underlying data with the original tensor._** What it does is actually change the metadata of the original tensor called `stride`. 

This `stride` tells PyTorch how to read the underlying memory with respect to the tensor.


In [54]:
tensor_1 = torch.tensor([[5,7,4],[1,3,2],[7,3,8]])
print("Original tensor:\n"+str(tensor_1))
print("Original tensor shape: "+str(tensor_1.shape))
print("Original tensor stride: "+str(tensor_1.stride()))

Original tensor:
tensor([[5, 7, 4],
        [1, 3, 2],
        [7, 3, 8]])
Original tensor shape: torch.Size([3, 3])
Original tensor stride: (3, 1)


In tensor_1 (original tensor), its stride can be accesed through the `stride()` method, and as you can see it returns a tuple of (3,1).

> <strong>Each value represents how many memory locations to traverse/skip until the next index in its respective dimensions. 

The first value will represent how many steps to reach the next index in $dim_0$, the second value will represent $dim_1$ and so on. Referring to the above exmaple, the first value (3) shows the next index on the 0th dimension of this tensor is located after 3 values.

<img src=../data/stride.png width=500 height=500>

In [55]:
view_tensor = tensor_1.view(-1,9)
print("Reshaped view tensor:\n"+str(view_tensor))
print("Reshaped view tensor shape: ", str(view_tensor.shape))
print("Stride of reshaped view tensor: "+ str(view_tensor.stride()))

Reshaped view tensor:
tensor([[5, 7, 4, 1, 3, 2, 7, 3, 8]])
Reshaped view tensor shape:  torch.Size([1, 9])
Stride of reshaped view tensor: (9, 1)


As you can see, `view()` of a tensor with a different shape has a different stride as well.

Like we mentioned before, the tensor obtained after performing `view()` **shares the same underlying data with the original tensor**, thus any changes made in the viewed tensor is reflected in the obtained tensor as well.

In [56]:
# fill tensor_1 with ones
tensor_1 = tensor_1.fill_(1)
print(view_tensor)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1]])


Notice that the values of `view_tensor` changes as the values of `tensor_1` changes.

Another thing to note is that `view()` only accepts _contiguous_ tensors. 
>The term **'contiguous'** refers to the continuity of the data stored in the tensor's memory layout. 

A great example of a non-contiguous tensor will be a transposed tensor.
Let's change the `tensor_1` to array ranges from `0-8`.

In [57]:
tensor_1 = torch.arange(0,9) #init
tensor_1 = tensor_1.view(3,3) #reshape
tensor_1 #the memory that stores the tensor becomes [0,1,2,3,4,5,6,7,8]

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [58]:
print("Transposed tensor: \n"+ str(tensor_1.T)) #after transpose, the memory that stores the tensor becomes [0,3,6,1,4,7,2,5,8]
print("Transposed tensor stride: "+ str(tensor_1.T.stride()))

Transposed tensor: 
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
Transposed tensor stride: (1, 3)


In [59]:
tensor_1.T.is_contiguous()

False

In [60]:
try:
    tensor_1.T.view(9)
except Exception as e:
    print(e)

view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.


So there are a few ways to tackle non-contiguous tensors. 

One of them is to call `tensor.contiguous()` to make them contiguous. PyTorch will make a new copy of the tensor in another memory location contiguously.

In [61]:
transposed = tensor_1.T.contiguous()
print("Transposed Tensor:\n" +str(transposed))
print("Contiguity of Tensor: " + str(transposed.is_contiguous()))

Transposed Tensor:
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
Contiguity of Tensor: True


In [62]:
t_view = transposed.view(1,9)
print(t_view)

tensor([[0, 3, 6, 1, 4, 7, 2, 5, 8]])


Another way is to call `tensor.reshape()`.

`tensor.reshape()` can operate on both contiguous and non-contiguous tensor. 

**It will be a view of input if continguous input was passed, otherwise it will allocate a new memory storage to store the reshaped tensor.**

In [63]:
transposed = tensor_1.T
print("Transposed tensor:", transposed, sep="\n")
print("Contiguity of Transposed tensor:", transposed.is_contiguous())
t_reshape = transposed.reshape(1,9)
print("Reshaped tensor:" , t_reshape, sep="\n")
print("Contiguity of Reshaped tensor:", t_reshape.is_contiguous())

Transposed tensor:
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
Contiguity of Transposed tensor: False
Reshaped tensor:
tensor([[0, 3, 6, 1, 4, 7, 2, 5, 8]])
Contiguity of Reshaped tensor: True


Since `transposed` tensor is non-contiguous, calling `transposed.reshape()` will return a copy of it that is contiguous.

In [64]:
# changing the value of t_reshape will not affect the values of transposed 
t_reshape[0,2] = 10
print("transposed tensor: \n" ,transposed)
print("reshaped tensor: \n" ,t_reshape)

transposed tensor: 
 tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
reshaped tensor: 
 tensor([[ 0,  3, 10,  1,  4,  7,  2,  5,  8]])


## 1.5 Tensors on CPU and GPU  

Throughout our course we will be using PyTorch with both CPU and GPU capabilities (CUDA Toolkit), this section will **show how to use tensors in both CPU and GPU.**
<br><br>
Before we utillize the GPU, the norm is that we check if cuda is available, and declare a `torch.device("cuda:0")` for later use.<br>Notation-wise, `cuda` refers to the cuda-enabled gpu and `:0` refers to the index of the GPU. This is useful when you have multiple GPUs.

In [65]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)

cuda:0


PyTorch allows us to seamlessly move data to and from our GPU to perform computations with the following methods:
- `torch.rand((shape),device="cuda")`- this method initializes the tensor in GPU memory.
- `tensor.to("cuda")`- this method returns a copy of the tensor in GPU memory
- `tensor.cuda()`- this method returns a copy of the tensor in GPU memory

In [66]:
tensor = torch.rand((2,3,4),device=device)
print(tensor)

tensor([[[0.9404, 0.5965, 0.1289, 0.3351],
         [0.6340, 0.5787, 0.6565, 0.8312],
         [0.3952, 0.4125, 0.4504, 0.9722]],

        [[0.4531, 0.5989, 0.0570, 0.2216],
         [0.7571, 0.2807, 0.3738, 0.3482],
         [0.9247, 0.1349, 0.4818, 0.3784]]], device='cuda:0')


In [67]:
# tensor_1 is initialized in CPU memory
tensor_1 = torch.rand((2,3,4))
print(tensor_1) 


tensor([[[0.4304, 0.8133, 0.0291, 0.4117],
         [0.2049, 0.9853, 0.8905, 0.7728],
         [0.2891, 0.0865, 0.3444, 0.1375]],

        [[0.4535, 0.2644, 0.3008, 0.4354],
         [0.2262, 0.4630, 0.2794, 0.0315],
         [0.2670, 0.5251, 0.4599, 0.0583]]])


In [68]:
tensor_2 = tensor_1.to("cuda:0")
print(tensor_2)

tensor([[[0.4304, 0.8133, 0.0291, 0.4117],
         [0.2049, 0.9853, 0.8905, 0.7728],
         [0.2891, 0.0865, 0.3444, 0.1375]],

        [[0.4535, 0.2644, 0.3008, 0.4354],
         [0.2262, 0.4630, 0.2794, 0.0315],
         [0.2670, 0.5251, 0.4599, 0.0583]]], device='cuda:0')


In [69]:
tensor_3 = tensor_1.cuda(device)
# or just tensor.cuda() if there is only one GPU
print(tensor_3)

tensor([[[0.4304, 0.8133, 0.0291, 0.4117],
         [0.2049, 0.9853, 0.8905, 0.7728],
         [0.2891, 0.0865, 0.3444, 0.1375]],

        [[0.4535, 0.2644, 0.3008, 0.4354],
         [0.2262, 0.4630, 0.2794, 0.0315],
         [0.2670, 0.5251, 0.4599, 0.0583]]], device='cuda:0')


Notice that these tensors are **stored in separate devices.** Hence, both separate tensors in respectively **CPU and GPU are not capable of performing operations with each other**.

In [70]:
try:
    print(tensor_1+tensor_2)
except Exception as e:
    print(e)

Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!


To check the type of device that the tensor is in, simply use `tensor.device`

In [71]:
print(tensor_1.device)
print(tensor_2.device)

cpu
cuda:0


# Exercise

**_TASK_**: Initialize a tensor of random integers ranging from 0-100 with **dimensions(5,8,7)**

In [72]:
torch.manual_seed(0)
# Your code
tensor = torch.randint(0,100,(5,8,7))
print(tensor)

tensor([[[44, 39, 33, 60, 63, 79, 27],
         [ 3, 97, 83,  1, 66, 56, 99],
         [78, 76, 56, 68, 94, 33, 26],
         [19, 91, 54, 24, 41, 69, 69],
         [49, 80, 81, 12, 63, 60, 95],
         [85, 22, 99, 11, 88, 78, 43],
         [96, 89, 71, 57, 83, 95, 82],
         [71, 40, 69, 73, 41, 11, 80]],

        [[ 3,  6, 76, 27, 99, 26, 63],
         [74, 75,  0, 18, 32, 68, 12],
         [77, 45, 10, 80, 48, 21, 19],
         [16, 81, 90, 82, 19, 44, 33],
         [69, 63,  9, 33, 19, 78, 35],
         [83, 22, 58, 35, 16, 46, 35],
         [77, 12,  5, 46, 56, 15, 84],
         [50,  8, 71, 47,  8, 75, 84]],

        [[84, 48, 44, 34, 19, 60,  7],
         [14, 75, 63, 13, 57, 33, 20],
         [49, 89, 93, 11, 28, 31, 77],
         [58, 84,  1, 70, 84, 90, 84],
         [69, 27, 70, 10, 41, 84, 19],
         [69,  5, 99, 72, 62, 42, 71],
         [14, 39, 71, 11, 50, 73, 30],
         [66, 87, 26, 19, 71,  6, 94]],

        [[91, 20, 85, 42, 75, 18,  1],
         [18, 61, 1

#### Expected Output :
```
tensor([[[44, 39, 33, 60, 63, 79, 27],
         [ 3, 97, 83,  1, 66, 56, 99],
         [78, 76, 56, 68, 94, 33, 26],
         [19, 91, 54, 24, 41, 69, 69],
         [49, 80, 81, 12, 63, 60, 95],
         [85, 22, 99, 11, 88, 78, 43],
         [96, 89, 71, 57, 83, 95, 82],
         [71, 40, 69, 73, 41, 11, 80]],

        [[ 3,  6, 76, 27, 99, 26, 63],
         [74, 75,  0, 18, 32, 68, 12],
         [77, 45, 10, 80, 48, 21, 19],
         [16, 81, 90, 82, 19, 44, 33],
         [69, 63,  9, 33, 19, 78, 35],
         [83, 22, 58, 35, 16, 46, 35],
         [77, 12,  5, 46, 56, 15, 84],
         [50,  8, 71, 47,  8, 75, 84]],

        [[84, 48, 44, 34, 19, 60,  7],
         [14, 75, 63, 13, 57, 33, 20],
         [49, 89, 93, 11, 28, 31, 77],
         [58, 84,  1, 70, 84, 90, 84],
         [69, 27, 70, 10, 41, 84, 19],
         [69,  5, 99, 72, 62, 42, 71],
         [14, 39, 71, 11, 50, 73, 30],
         [66, 87, 26, 19, 71,  6, 94]],

        [[91, 20, 85, 42, 75, 18,  1],
         [18, 61, 12, 78, 50, 43, 28],
         [39, 82,  7, 60, 88, 78, 96],
         [98, 15, 18, 66, 95, 72, 84],
         [12, 77, 42, 84, 69, 18, 95],
         [ 6, 74, 43, 33, 64,  0, 12],
         [15, 51, 12, 78,  2, 44,  8],
         [23, 36, 45, 78, 68, 40, 15]],

        [[21,  3, 80, 18, 21, 41, 81],
         [47, 32, 32, 92, 93, 33, 86],
         [37, 88, 20, 65, 30, 13, 65],
         [95, 33, 96, 52, 32, 35, 75],
         [69, 74, 73,  3, 57, 43, 48],
         [20, 47, 45, 38, 32, 94, 67],
         [43, 22, 55, 45, 93, 69, 91],
         [78, 40, 96, 37, 64, 67, 86]]])
```

**_TASK_**: Slice out part of the tensor with indices $(0\rightarrow 4,3\rightarrow 6,1\rightarrow 6)$ and name it `slice_1`

In [73]:
slice_1 = tensor[0:5,3:7,1:7]
print(slice_1)

tensor([[[91, 54, 24, 41, 69, 69],
         [80, 81, 12, 63, 60, 95],
         [22, 99, 11, 88, 78, 43],
         [89, 71, 57, 83, 95, 82]],

        [[81, 90, 82, 19, 44, 33],
         [63,  9, 33, 19, 78, 35],
         [22, 58, 35, 16, 46, 35],
         [12,  5, 46, 56, 15, 84]],

        [[84,  1, 70, 84, 90, 84],
         [27, 70, 10, 41, 84, 19],
         [ 5, 99, 72, 62, 42, 71],
         [39, 71, 11, 50, 73, 30]],

        [[15, 18, 66, 95, 72, 84],
         [77, 42, 84, 69, 18, 95],
         [74, 43, 33, 64,  0, 12],
         [51, 12, 78,  2, 44,  8]],

        [[33, 96, 52, 32, 35, 75],
         [74, 73,  3, 57, 43, 48],
         [47, 45, 38, 32, 94, 67],
         [22, 55, 45, 93, 69, 91]]])


#### Expected Output :
```
tensor([[[91, 54, 24, 41, 69, 69],
         [80, 81, 12, 63, 60, 95],
         [22, 99, 11, 88, 78, 43],
         [89, 71, 57, 83, 95, 82]],

        [[81, 90, 82, 19, 44, 33],
         [63,  9, 33, 19, 78, 35],
         [22, 58, 35, 16, 46, 35],
         [12,  5, 46, 56, 15, 84]],

        [[84,  1, 70, 84, 90, 84],
         [27, 70, 10, 41, 84, 19],
         [ 5, 99, 72, 62, 42, 71],
         [39, 71, 11, 50, 73, 30]],

        [[15, 18, 66, 95, 72, 84],
         [77, 42, 84, 69, 18, 95],
         [74, 43, 33, 64,  0, 12],
         [51, 12, 78,  2, 44,  8]],

        [[33, 96, 52, 32, 35, 75],
         [74, 73,  3, 57, 43, 48],
         [47, 45, 38, 32, 94, 67],
         [22, 55, 45, 93, 69, 91]]])
```

**_TASK_**: Produce 5 chunks of tensors where $dim = 0$ from `slice_1` and put it in a list: `list_1`

In [74]:
list_1 = slice_1.chunk(5)
for chunk in list_1:
    print(chunk)

tensor([[[91, 54, 24, 41, 69, 69],
         [80, 81, 12, 63, 60, 95],
         [22, 99, 11, 88, 78, 43],
         [89, 71, 57, 83, 95, 82]]])
tensor([[[81, 90, 82, 19, 44, 33],
         [63,  9, 33, 19, 78, 35],
         [22, 58, 35, 16, 46, 35],
         [12,  5, 46, 56, 15, 84]]])
tensor([[[84,  1, 70, 84, 90, 84],
         [27, 70, 10, 41, 84, 19],
         [ 5, 99, 72, 62, 42, 71],
         [39, 71, 11, 50, 73, 30]]])
tensor([[[15, 18, 66, 95, 72, 84],
         [77, 42, 84, 69, 18, 95],
         [74, 43, 33, 64,  0, 12],
         [51, 12, 78,  2, 44,  8]]])
tensor([[[33, 96, 52, 32, 35, 75],
         [74, 73,  3, 57, 43, 48],
         [47, 45, 38, 32, 94, 67],
         [22, 55, 45, 93, 69, 91]]])


#### Expected Output :
```
tensor([[[91, 54, 24, 41, 69, 69],
         [80, 81, 12, 63, 60, 95],
         [22, 99, 11, 88, 78, 43],
         [89, 71, 57, 83, 95, 82]]])
tensor([[[81, 90, 82, 19, 44, 33],
         [63,  9, 33, 19, 78, 35],
         [22, 58, 35, 16, 46, 35],
         [12,  5, 46, 56, 15, 84]]])
tensor([[[84,  1, 70, 84, 90, 84],
         [27, 70, 10, 41, 84, 19],
         [ 5, 99, 72, 62, 42, 71],
         [39, 71, 11, 50, 73, 30]]])
tensor([[[15, 18, 66, 95, 72, 84],
         [77, 42, 84, 69, 18, 95],
         [74, 43, 33, 64,  0, 12],
         [51, 12, 78,  2, 44,  8]]])
tensor([[[33, 96, 52, 32, 35, 75],
         [74, 73,  3, 57, 43, 48],
         [47, 45, 38, 32, 94, 67],
         [22, 55, 45, 93, 69, 91]]])
```

**_TASK_**: Concatenate the first and third chunk together at dimension 2 and name it `cat_1`

In [75]:
cat_1 = torch.cat((list_1[0],list_1[2]),2)
print(cat_1)

tensor([[[91, 54, 24, 41, 69, 69, 84,  1, 70, 84, 90, 84],
         [80, 81, 12, 63, 60, 95, 27, 70, 10, 41, 84, 19],
         [22, 99, 11, 88, 78, 43,  5, 99, 72, 62, 42, 71],
         [89, 71, 57, 83, 95, 82, 39, 71, 11, 50, 73, 30]]])


#### Expected Output :
```
tensor([[[91, 54, 24, 41, 69, 69, 84,  1, 70, 84, 90, 84],
         [80, 81, 12, 63, 60, 95, 27, 70, 10, 41, 84, 19],
         [22, 99, 11, 88, 78, 43,  5, 99, 72, 62, 42, 71],
         [89, 71, 57, 83, 95, 82, 39, 71, 11, 50, 73, 30]]])
```

**_TASK_**: Add `tensor_1` and `tensor_2` five times and store the result in the same storage location of `tensor_2`.

In [76]:
tensor_1 = torch.tensor([1, 0, -1, -1, 0, 1])
tensor_2 = torch.tensor([[21, 45, 68, 32, 1, 0],
                        [93, 32, 33, 20, 5, 72]])
tensor_ans = tensor_2.add_(tensor_1.mul(5))

In [77]:
loc_tensor_1 = tensor_1.data_ptr()
loc_tensor_2 = tensor_2.data_ptr()
loc_tensor_ans = tensor_ans.data_ptr()
print("tensor_ans: \n" + str(tensor_ans))
print("\nIs tensor storage location of tensor_ans same as tensor storage location of tensor_2: " + str(loc_tensor_ans == loc_tensor_2))

tensor_ans: 
tensor([[26, 45, 63, 27,  1,  5],
        [98, 32, 28, 15,  5, 77]])

Is tensor storage location of tensor_ans same as tensor storage location of tensor_2: True


#### Expected Output :
```
tensor_ans: 
tensor([[26, 45, 63, 27,  1,  5],
        [98, 32, 28, 15,  5, 77]])

Is tensor storage location of tensor_ans same as tensor storage location of tensor_2: True
```

**_TASK_**: Lets say right now we want to have **two** 8-bit RGB image with the size of 228 x 228, try to randomly initialize the tensors with the detail given 
(height, width, channel).

*Hint* : Use `torch.randint`

In [78]:
# Intialize the tensors
tensor_1 = torch.randint(0,256,(228,228,3))
tensor_2 = torch.randint(0,256,(228,228,3))

print("First 10 values for tensor 1 : ", tensor_1[0:10,0,0])
print("First 10 values for tensor 2 : ", tensor_2[0:10,0,0])

First 10 values for tensor 1 :  tensor([239, 194, 220, 114, 159,  42, 211, 211, 207, 222])
First 10 values for tensor 2 :  tensor([111, 155,  17, 170, 220, 237,  19,  18, 127, 185])


#### Expected Output :
``` 
First 10 values for tensor 1 :  tensor([239, 194, 220, 114, 159,  42, 211, 211, 207, 222])
First 10 values for tensor 2 :  tensor([111, 155,  17, 170, 220, 237,  19,  18, 127, 185])
```

It is impossible to perform matric multiplication on a 3D tensor, therefore we have to reshape it into a 2D tensor.

**_TASK_**: It this case, we would like to change the order of dimension of the tensor to shape$(channel, height, width)$ so that when we reshape, it would become $(channel, height \times width)$

*hint* : Use `tensor.permute`

In [79]:
# Change the order of the tensor dimension
tensor_1 = tensor_1.permute(2,0,1)
tensor_2 = tensor_2.permute(2,0,1)

print(tensor_1.shape)
print(tensor_2.shape)

torch.Size([3, 228, 228])
torch.Size([3, 228, 228])


#### Expected Output :
``` 
torch.Size([3, 228, 228])
torch.Size([3, 228, 228])
```

**_TASK_**: Perform reshape on the tensor

*hint* : Use `tensor.view`

In [80]:
# Reshape the tensor
tensor_1 = tensor_1.view(3,-1)
tensor_2 = tensor_2.view(3,-1)

print(tensor_1.shape)
print(tensor_1.shape)

torch.Size([3, 51984])
torch.Size([3, 51984])


#### Expected Output :
``` 
torch.Size([3, 51984])
torch.Size([3, 51984])
```

**_TASK_**: Perform matric multiplication between the tensors, take note that you might need to transpose to match the shape (3x3)

In [81]:
# Perform matric multiplication
tensor_mm = torch.mm(tensor_1,tensor_2.t())

print(tensor_mm)

tensor([[846356565, 849680903, 849140043],
        [842706582, 849543264, 846890670],
        [840797074, 846055878, 845897280]])


#### Expected Output :
``` 
tensor([[846356565, 849680903, 849140043],
        [842706582, 849543264, 846890670],
        [840797074, 846055878, 845897280]])
```

**_TASK_**: Initialize a **gpu device.** Then, initialize a random tensor with any size and store it in the device.

In [82]:
# initialize cuda device
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
tensor = torch.rand((2,3,6), device=device)
print(tensor)

tensor([[[0.3990, 0.5167, 0.0249, 0.9401, 0.9459, 0.7967],
         [0.4150, 0.8203, 0.2290, 0.9096, 0.1183, 0.0752],
         [0.4092, 0.9601, 0.2093, 0.1940, 0.8909, 0.4387]],

        [[0.3570, 0.5454, 0.8299, 0.2099, 0.7684, 0.4290],
         [0.2117, 0.6606, 0.1654, 0.4250, 0.9927, 0.6964],
         [0.2472, 0.7028, 0.7494, 0.9303, 0.0494, 0.0750]]], device='cuda:0')


#### Expected Output :
``` 
tensor([[[0.3990, 0.5167, 0.0249, 0.9401, 0.9459, 0.7967],
         [0.4150, 0.8203, 0.2290, 0.9096, 0.1183, 0.0752],
         [0.4092, 0.9601, 0.2093, 0.1940, 0.8909, 0.4387]],

        [[0.3570, 0.5454, 0.8299, 0.2099, 0.7684, 0.4290],
         [0.2117, 0.6606, 0.1654, 0.4250, 0.9927, 0.6964],
         [0.2472, 0.7028, 0.7494, 0.9303, 0.0494, 0.0750]]], device='cuda:0')
```